spring:
  datasource:
    url: "jdbc:h2:mem:spring-basic;MODE=MYSQL"
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 5000

allowed :
  mapping : "/**"
  header : "**"
  origins : "http://localhost:3000"
  methods : "*"
  age : 1800
  credentials : false